import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/app/_libs/components/header/header';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import manifest from '@/../public/manifest.json';
import { ThemeProvider } from '@mui/material';
import MuiTheme from '@/app/_libs/mui-theme';
import { GoogleAnalytics } from '@next/third-parties/google';

const inter = Inter({ subsets: ['latin'] });

const APP_NAME = manifest.name;
const APP_DEFAULT_TITLE = manifest.name;
const APP_TITLE_TEMPLATE = '%s - ' + manifest.name;
const APP_DESCRIPTION = 'Best PWA app in the world!';

export const metadata: Metadata = {
  applicationName: APP_NAME,
  icons: {
    icon: '/favicon.png',
  },
  title: {
    default: APP_DEFAULT_TITLE,
    template: APP_TITLE_TEMPLATE,
  },
  description: APP_DESCRIPTION,
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: APP_DEFAULT_TITLE,
    // startUpImage: [],
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: 'website',
    siteName: APP_NAME,
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
  twitter: {
    card: 'summary',
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
};

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {process.env.GAID && <GoogleAnalytics gaId={process.env.GAID} />}
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={MuiTheme}>
            <section className="relative h-screen overflow-hidden bg-[#eff2fc]">
              <Header />
              <div className="transition-all absolute sm:left-[28px] sm:right-[16px] sm:bottom-[16px] top-[108px] sm:top-[72px] left-0 right-0 bottom-0 bg-white overflow-hidden rounded-t-[28px] sm:rounded-[28px] z-0 bg-[#fdfcff]">
                <main className="overflow-auto h-full p-7 pr-5">
                  {children}
                </main>
              </div>
            </section>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
